export const GENRE_LIST_REQUEST = "GENRE_LIST_REQUEST"
export const GENRE_LIST_REQUEST_SUCCESS = "GENRE_LIST_REQUEST_SUCCESS"
export const GENRE_LIST_REQUEST_ERROR = "GENRE_LIST_REQUEST_ERROR"

export const LABEL_LIST_REQUEST = "LABEL_LIST_REQUEST"
export const LABEL_LIST_REQUEST_SUCCESS = "LABEL_LIST_REQUEST_SUCCESS"
export const LABEL_LIST_REQUEST_ERROR = "LABEL_LIST_REQUEST_ERROR"
