export const RELEASE_LIST_REQUEST = "RELEASE_LIST_REQUEST"
export const RELEASE_LIST_REQUEST_SUCCESS = "RELEASE_LIST_REQUEST_SUCCESS"
export const RELEASE_LIST_REQUEST_ERROR = "RELEASE_LIST_REQUEST_ERROR"

export const TOP_LIST_REQUEST = "TOP_LIST_REQUEST"
export const TOP_LIST_REQUEST_SUCCESS = "TOP_LIST_REQUEST_SUCCESS"
export const TOP_LIST_REQUEST_ERROR = "TOP_LIST_REQUEST_ERROR"
